### PR TITLE
WIP: Improve crate compilation times

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
Hopefully this will make improvements towards #1017. As I'm going I'll try to post numbers so we can see how changes affect compilation times.

Initial breakdown of compilation times using `cargo build -Ztimings`: 
[timings.zip](https://github.com/rust-lang-nursery/mdBook/files/3772170/timings.zip)

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
After updating `Cargo.lock` with `cargo update` and manually upgrading `env_logger` from 0.6 to 0.7, compilation time dropped from 97.7s to 85.9s.

I'm guessing the compilation improvements are because we aren't compiling multiple versions of the same crate.

[bump-dependency-versions.zip](https://github.com/rust-lang-nursery/mdBook/files/3772192/bump-dependency-versions.zip)

**Comment by Michael-F-Bryan** [comment]
For some reason, removing the itertools crate (it was only used two or three times to skip an allocation when concatenating lines) and running `cargo clean && cargo build -Ztimings` again dropped compilation times on my machine to 60s.

[remove-itertools.zip](https://github.com/rust-lang-nursery/mdBook/files/3772391/remove-itertools.zip)

I don't think `itertools` was to blame... maybe it had something to do with build order or a warm page cache?

**Comment by Dylan-DPC** [comment]
@ehuss yeh most likely this will be a breaking change so might as well release a new major version when finished which would also justify the msvr bump

**Comment by Michael-F-Bryan** [comment]
I'm not sure why, but removing `toml_query` from the build actually **increased** compile times from 60s to 77s...

New dependency graph:

dependency-graph

Timings: [remove-toml-query.zip](https://github.com/rust-lang-nursery/mdBook/files/3772841/remove-toml-query.zip)

**Comment by Michael-F-Bryan** [comment]
I swapped out iron with [simple-server](https://github.com/steveklabnik/simple-server) and the "build" stage in CI went from 4 mins 1 second to 3 mins 52 seconds.

dependency-graph


Timings: 
[remove-iron.zip](https://github.com/rust-lang-nursery/mdBook/files/3772963/remove-iron.zip)

**Comment by ehuss** [comment]
@Michael-F-Bryan Is this ready to go? You still have WIP in the title.   I really like the changes, and it looks good to go to me.

**Comment by Michael-F-Bryan** [comment]
I'm not certain it makes much of a difference. When running on my laptop I found the results super noisy and inconsistent, and I wasn't confident the compile time improvements weren't just due to something like the page cache or CPU governor changing clock frequency...

**Comment by ehuss** [comment]
Thanks for getting this going!  Closed via #1211.

**Pull request closed without merging**
