### PR TITLE
Support space as seperator between language and additional class in c…

### PR DESCRIPTION
**Pull request by tuyen-at-work**
…ode block

This PR try to resolve this issue: https://github.com/rust-lang/mdBook/issues/1384

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks!  It looks like rustdoc will be making a similar change (https://github.com/rust-lang/rust/pull/78429).  Maybe this should match its behavior and also support the tab character?  (I don't think it should bother with the curly brace issue.)
Unfortunately, per https://github.com/rust-lang/rust/pull/78429#issuecomment-718340447, it doesn't seem like there is much agreement on how this should work, but spaces and tabs seem reasonable.  I'd also like to wait until the rustdoc changes land.

**Comment by tuyen-at-work** [comment]
@ehuss as your comment, GitHub supports `,`, `space` and `\t`. VS Code supports `space` and `\t` but not `,`. They are the biggest guys in the market. So I think it is most flexible to support all 3 chars, like GitHub does. I think as long as GitHub supports it, other implementation will follow suits.

**Comment by jyn514** [comment]
> Thanks! It looks like rustdoc will be making a similar change (rust-lang/rust#78429). Maybe this should match its behavior and also support the tab character?

Just to clarify - rustdoc already splits on spaces (in fact, it splits on almost anything that's not a letter). https://github.com/rust-lang/rust/pull/78429 is removing delimiters, not adding more.

**Review by ehuss — APPROVED** [review]
I went ahead and pushed a change to add tab to be consistent with rustdoc and GitHub.

**Pull request merged**
