### PR TITLE
Add CLI tests

### PR DESCRIPTION
**Pull request by notriddle**
Part of #1568

### CODE REVIEW

**Comment by notriddle** [comment]
Finally, I managed to make a version that actually works correctly under Windows.

**Comment by joshrotenberg** [comment]
This is great, thanks for kicking it off!

Obviously there is a lot to test, and doing it in small chunks makes sense. One suggestion I have would be to make a `test/cli` top level module, and then separate each test file to match the `cli` files, so like:

```
tests/cli/mod.rs  - any shared test stuff can go here
tests/cli/build.rs - all tests for the build command
...
```

**Comment by notriddle** [comment]
@joshrotenberg

I can do that. I don't really like the result, because you're required to have a top-level `.rs` file for the test harness to actually run the tests. But it is doable.

**Review by ehuss — APPROVED** [review]
Thanks!  I went ahead and rebased to resolve the conflict.  I'm slightly concerned about adding so many dependencies, but I don't think there is an easy way around that.

@joshrotenberg I'm not sure if you had any more feedback on this, but I'm going to go ahead and merge. If you had anything else to add, please let me know.

**Pull request merged**
