### PR TITLE
Update pulldown-cmark version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Linked to https://github.com/rust-lang/rust/pull/92252.

### CODE REVIEW

**Review by ehuss — APPROVED** [review]
Thanks!

**Comment by GuillaumeGomez** [comment]
Do you know when will be the next release? We need it for https://github.com/rust-lang/rust/pull/92252.

**Comment by ehuss** [comment]
I'll probably do a release next week or so. However, I wouldn't delay that PR just to avoid a duplicate in `Cargo.lock`. There are duplicates all the time, and I don't think there is a strong need to avoid them, especially if they'll eventually get resolved.

**Comment by GuillaumeGomez** [comment]
We merged the PR so no hurry. Can you ping me once you have a new release please?

**Comment by ehuss** [comment]
Absolutely!

**Comment by GuillaumeGomez** [comment]
Thanks a lot!

**Pull request merged**
