### PR TITLE
Add hidelines code class to enable hiding in non-Rust blocks

### PR DESCRIPTION
**Pull request by dtolnay**
```toml,hidelines

---

Screenshot from 2020-11-11 22-49-31

---

Screenshot from 2020-11-11 22-49-44

### CODE REVIEW

**Comment by dtolnay** [comment]
Possible future extension: <code>```language,hidelines=@</code> for hiding based on a symbol other than `#`.

**Comment by ehuss** [comment]
Just a heads up, there's another PR for something similar: #1339.

I won't have time to do reviews for a little while, but if you could maybe take a look at that PR and give feedback on the design?  I'm a bit uncertain on how to approach this, but on the surface that PR seems to be fairly flexible.

**Comment by dtolnay** [comment]
I definitely don't like that approach. :confused: Left a comment.

**Comment by dtolnay** [comment]
Superseded by #2093!

**Pull request closed without merging**
