### PR TITLE
Fix stray spacing of code blocks containing injected main

### PR DESCRIPTION
**Pull request by dtolnay**
For example see the first code block in https://doc.rust-lang.org/1.47.0/book/ch03-02-data-types.html.

````markdown
```rust
let guess: u32 = "42".parse().expect("Not a number!");
```
````

<br>

### Before:

Screenshot from 2020-11-05 21-31-53

<br>

### After:

Screenshot from 2020-11-05 21-32-20

### CODE REVIEW

**Comment by ehuss** [comment]
Hm, so I'm uncertain about this change. There's a problem that on narrower screens, the buttons will overlap the code (see #1322).  I think this could make the problem worse.  I would kinda like to have a solution for the overlap problem first before deciding what to do here.  

I'm uncertain if it makes sense to have a blank space on every example?  Some other docs sites do that (like [docusaurus](https://docusaurus.io/docs/en/commands)).  

Another option is to hide the buttons with a mouseover (like [bookdown](https://bookdown.org/yihui/bookdown/r-code.html)), but that doesn't work on mobile, and may not be discoverable and too magical.

Another option would be to hang the icons off the right side, but I don't know what that would look like, or if there would be enough space.

I don't really know what would be a good approach.

**Comment by dtolnay** [comment]
Good call.

I since realized I do not want buttons anyway on my site (`​```rust,noplayground` &amp; `playground = { copyable = false }`) and without buttons the blank line does not appear, so I no longer need this -- feel free to close.

**Comment by pickfire** [comment]
Is it possible to use a css based approach to do some padding on small screens?

Originally, I opened an issue in https://github.com/rust-unofficial/patterns/issues/155. I was searching for issues in this repo and came across this. I believe this would not look so good on desktop or even tablets, maybe very small screens with very long first line would be affected by this, I don't think I have seen any in the wild. Even if I did, it is less annoying than the extra space which leads to me searching issues in this repo.

**Comment by Dylan-DPC** [comment]
closing this, we can discuss other approaches on the issue or in a new pr

**Comment by dtolnay** [comment]
I filed #1433 to track in mdBook.

**Pull request closed without merging**
