### PR TITLE
Markdown page

### LINKED ISSUE #1708: Document how to include static files and linking to them
The documentation should include some information on how to include static files (such as images), and how to link to them.

### PR DESCRIPTION
**Pull request by joshrotenberg**
Adds a new page about markdown to the guide. 

Fixes #1708.

### CODE REVIEW

**Comment by ehuss** [comment]
This looks like a great start!  Let me know if you want any feedback yet.

I'm going to work on the documentation a bit this weekend, and this will be great to link to.

**Comment by joshrotenberg** [comment]
> This looks like a great start! Let me know if you want any feedback yet.
> 
> I'm going to work on the documentation a bit this weekend, and this will be great to link to.

Added a few more basic things.  I think it's enough of the basics with links elsewhere for more. Let me know if you think I should include any other elements or change things around.

**Review by ehuss — APPROVED** [review]
Thanks!

**Comment by ehuss** [comment]
@joshrotenberg I posted #1710 with an update to the documentation, which includes some additions to this page. Would you be willing to look over that PR?  I realize it is kinda large, but I would appreciate if someone could at least skim it.

**Pull request merged**
