### PR TITLE
Add -m arg to watch/serve to only watch .md files

### PR DESCRIPTION
**Pull request by 9999years**
Sometimes, a change to a garbage file (in my case, Vim swap files) in the source directory will cause a book rebuild, which is unnecessary, particularly in `serve` mode where it triggers a visually noisy page refresh.

This PR adds a `-m` / `--markdown-only` switch to the `watch` and `serve` subcommands, which causes the file-watcher to ignore changes in files that don't end in `.md`.

### CODE REVIEW

**Comment by 9999years** [comment]
This might close or partially close #383. We could also consider using a user-supplied regex for files to watch.

**Comment by Michael-F-Bryan** [comment]
Instead of using a command-line flag (which you have to remember every time you run `mdbook`) that *only* whitelists markdown files, I'd prefer a more flexible solution where you can provide your own glob patterns to ignore.

For example,

```toml
[build]
# provide a list of globs to ignore
ignored = [
  "*.tmp",
  "*~",
]

# or use your gitignore file (e.g. with https://crates.io/crates/ignore)

[build]
ignored = "gitignore"
```

Also, should this alter *just* the behaviour of file watcher in `mdbook watch` and `mdbook serve`, or could it also be used to prevent things from accidentally being copied to the `book/` output directory?

**Comment by 9999years** [comment]
I would be fine with either of those, although I feel like ignoring editor-dependent things like swap files should be an end-user task, not bundled with the repository; I feel the same way about putting `.*.swp` in a `.gitignore`; they belong, in my opinion, in a global `.gitignore`.

I only have a narrow need here: excluding my Vim swap files. Any solution that can accomplish that is fine by me. If you’d like to decide on a more flexible system, I’ll see what I can do to help implement it.

**Comment by ehuss** [comment]
I'm going to close as this is somewhat outdated.  Support for .gitignore has been added, and there is more discussion at #1187 and #1440 to configure what to ignore.  Thanks for the PR, though!

**Pull request closed without merging**
