### PR TITLE
Add Bibliography with Bibtex-format support

### PR DESCRIPTION
**Pull request by francisco-perez-sorrosal**
Allows adding a bibliography in [BibTex format](http://www.bibtex.org/Format/) to your book and reference the citation keys in your markdown files.

Instructions have been added to the guide.

This is related to issue #1350

### CODE REVIEW

**Comment by ehuss** [comment]
Is this something that can exist as an external plugin?  I would prefer to minimize the maintenance burden on the project, and extensions like this seem like they would be better to be used as a separate addon.

**Comment by francisco-perez-sorrosal** [comment]
Hi @ehuss. I understand your concern about minimizing the impact of a feature like this in the project structure. When I implemented it, I tried to impact minimally the project, by defining meaningful abstractions (e.g. `BibItem`, `Bibliography`...) according to the already present ones in the project regarding the structure of an mdBook (such as `Chapter` or `BookItem`...) Bibliographies are part of any book so the abstract concept is there.

I had no previous Rust experience, and I basically implemented this functionality in just a week starting from scratch with both Rust and the mdBook project. What do you mean by `external plugin`? I've been looking for `plugin` in the mdBook doc and the project structure and I can't find anything related to plugins in the mdBook project.

**Comment by francisco-perez-sorrosal** [comment]
BTW I think issue #1371 is related also for some bibliography support too in mdBook.

**Comment by ehuss** [comment]
> What do you mean by `external plugin`?

Ah, I mean a [preprocessor](https://rust-lang.github.io/mdBook/for_developers/preprocessors.html).  A preprocessor can make arbitrary changes to the book content. ([Plugins](https://github.com/rust-lang/mdBook/#3rd-party-plugins) sort of loosely refer to either preprocessors or renderers.)

**Comment by francisco-perez-sorrosal** [comment]
This can be done now through [this plugin/preprocessor](https://github.com/francisco-perez-sorrosal/mdbook-bib).
Crates:  https://crates.io/crates/mdbook-bib
Src/Binaries: https://github.com/francisco-perez-sorrosal/mdbook-bib/releases/tag/v0.0.3

**Pull request closed without merging**
