### PR TITLE
Add nix to default languages

### LINKED ISSUE #2261: Add nix-lang highlighting by default
### Problem

I'm using mdbook for a nix project and [highlightjs](https://highlightjs.readthedocs.io/en/latest/supported-languages.html) supports the nix-lang but mdbook [disables](https://rust-lang.github.io/mdBook/format/theme/syntax-highlighting.html) it by default.

### Proposed Solution

Vendor a highlight,js version with nix-lang support.

### Notes

This would probably be sensible since nix and rust is a pretty popular tooling combination and things like rustlings even have nix instructions and files by default.

### PR DESCRIPTION
**Pull request by Janik-Haag**
closes #2261

While I could maintain my own highlight.js for my Project, this would probably benefit a few users. Esp. since mdBook is already quite common in the nix-community, for example the [Nix Reference Manual](https://nixos.org/manual/nix/stable/language/index.html) uses it.

### CODE REVIEW

**Comment by deemp** [comment]
@ehuss, please, review. I'd like to use Nix highlighting in [numtide/devshell](https://github.com/numtide/devshell) docs.

**Comment by Janik-Haag** [comment]
You can relatively easily use it already, but native support would be nicer.
I'm already deploying it for nixos-dns, see here for the code https://github.com/Janik-Haag/NixOS-DNS/blob/main/docs/default.nix#L30

**Review by jalil-salame — COMMENTED** [review]
Looks good to me

**Comment by deemp** [comment]
@ehuss, @jalil-salame, can you please merge?

**Comment by jalil-salame** [comment]
@deemp I just reviewed it, I don't have merge rights c:

**Comment by ehuss** [comment]
Thanks for the PR! Unfortunately we are not able to update highlight.js. Can you make sure this is built with 10.1.1?

**Comment by Janik-Haag** [comment]
Hey @ehuss I updated highlight js with the exact 10.1.1 version. Is there anything else I should do?

**Review by ehuss — APPROVED** [review]
Thanks!

**Pull request merged**
