### PR TITLE
Update highlight.js

### PR DESCRIPTION
**Pull request by maniyar1**
Updates to 10.1.1, with support for new languages added to the common set (#1275).
Built with:
common languages + D, handlebars, haskell, julia, scala, x86asm, armasm, yaml
Size difference:
New highlight.js: 132KiB
Old highlight.js: 84KiB

New highlight.js compressed: 48KiB
Old highlight.js compressed: 36KiB
So on average each request will be 12KiB more data (total payload is around 800KiB from my test).

I went through and double-checked that I didn't drop any languages, but a second pair of eyes couldn't hurt.

Full language list: 
```
    .properties
    C#
    Diff
    Json
    Less
    Nginx config
    Perl 
    Ruby
    Shell session
    YAML
    Apache
    C++
    Go
    Java
    Lua
    Objective-C
    Plain Text
    Rust
    Swift
    Bash
    C-like foundation
    HTML, XML
    JavaScript
    Makefile
    PHP
    Python
    SCSS
    TOML, also INI
    C
    CSS
    CoffeeScript
    HTTP
    Kotlin
    Markdown
    PHP Template
    Python REPL
    SQL
    Typescript
    D
    handlebars
    haskell
    julia
    scala
    x86asm
    armasm
    yaml
```

### CODE REVIEW

**Comment by colman-humphrey** [comment]
It would be great to get R support if possible. Since this highlight update is (necessarily) replacing a block of code, would adding it to this PR be possible (instead of another block replacement)?

I think (could be wrong) that R is the most popular language not yet supported (after the above change)

**Comment by maniyar1** [comment]
For me the easiest way would be to just regenerate the file, but it's pretty trivial to add R so I'll go ahead and add it in, surprised it's not in there already now that you mention it...

**Comment by colman-humphrey** [comment]
Thanks @maniyar1 !

**Comment by indiv0** [comment]
Would it be possible to add lisp support as well?

**Pull request merged**
