### PR TITLE
Build Docker image

### PR DESCRIPTION
**Pull request by kravemir**
Useful for GitLab CI. Compared to job installing `mdBook`, runtime decreased from `8m 30s` to `1m 18s`, which saves lots of time.

For example, can be used with job declaration mentioned in #813:

```yaml
pages:
  # https://hub.docker.com/_/rust/
  image: "kravemir/mdbook:0.2.1"
  stage: pages
  script:
    - mkdir public-tmp
    - ./bin/copyJavadocToBook.sh
    - mdbook build docs
    - cp -r docs/book/* public-tmp
    - mv public-tmp public
    - find $PWD/public
  artifacts:
    paths:
      - public
```

I had built it for myself and pushed to https://hub.docker.com/r/kravemir/mdbook/, with command:

```bash
./bin/releaseDocker.sh kravemir 0.2.1
```

IMHO: there's lots of space for improvements, but this provides at least initial working image, which can be used to build mdBook GitLab Pages with GitLab Runner quite easily.

### CODE REVIEW

**Comment by anisimovsergey** [comment]
I realy like the idea of using mdbook via Docker but the resulting image is quite big, aroung 1.6 Gb. Would it be better to use something like this:

```Dockerfile
FROM ekidd/rust-musl-builder AS builder

ARG VERSION

RUN cargo install mdbook --vers ${VERSION} --no-default-features

FROM alpine:latest

COPY --from=builder \
    /usr/local/bin/mdbook \
    /usr/local/bin/

CMD /usr/local/bin/mdbook
```

The resulting image is around 17Mb in this case.

**Comment by Dylan-DPC** [comment]
@ehuss thoughts on this?

**Comment by ehuss** [comment]
I'm not sure I understand the motivation.  It seems to me that it would be much easier to use a pre-built binary.  It should download and be usable much faster than getting a docker image.  I'm not familiar with GitLab Runner, but some more context and motivation would be helpful.

**Comment by moikot** [comment]
The image produced is quite large - 557 Mb. Here is a [Dockerfile](https://github.com/moikot/mdbook/blob/master/Dockerfile) which is producing [an image](https://hub.docker.com/r/moikot/mdbook/tags) which is 6.65 Mb only.

**Comment by ehuss** [comment]
I'm going to close this since there hasn't been much activity for a while (and the 500Mb image size sounds worrisome).  I recommend people to just download the pre-built binaries offered here on GitHub if possible.

**Comment by AndreaGiardini** [comment]
@moikot I think it would be nice to have an official docker image released by the mdbook project.
This is extremely useful when running in CI (Gitlab, but not only).
Would you be willing to merge the Dockerfile into the main mdbook repo?

@ehuss what is your opinion about releasing a docker image together with the offical mdbook relases?

**Comment by moikot** [comment]
@AndreaGiardini I can prepare a PR for the Dockerfile, it's not a problem.

**Comment by ehuss** [comment]
@AndreaGiardini can you describe the use case or motivation for a docker image as opposed to just downloading a pre-built executable?  It seems like the latter should be much more lightweight. I would prefer not to add more maintenance burden to the release process.

**Comment by AndreaGiardini** [comment]
Hi @ehuss 
Docker images make it much easier to run in container-based environments (e.g. Kubernetes) compared to the classic executable. Especially for CI/CD this could be a great addition.
If you are already using github actions setting up a pipeline for publishing a docker image at every release it's not that difficult and requires minimal effort. 

The advantage would be also to have one official image rather than dozens of unofficial ones ( https://hub.docker.com/search?q=mdbook&type=image ). As you can see from the number of people creating custom mdbook docker images, the request for something like that is definitely there!

**Pull request closed without merging**
